version: "3.8"
services:
  app:
    container_name: glfw
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: development
      args:
        - USERNAME=${CONTAINER_USER}
    volumes:
      # Host workspace
      - type: bind
        source: ${HOST_WORKSPACE}
        target: ${CONTAINER_WORKSPACE}
        consistency: cached
      # X11 settings
      - /${HOME}/.Xauthority:/home/${CONTAINER_USER}/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      # ZMQ socket
      # for inter container communication via ZeroMQ
      - /tmp/zmq:/tmp/zmq 
    environment:
      - DISPLAY=:$DISPLAY
    user: ${CONTAINER_USER}
    tty: true
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    #user: "${UID}:${GID}"