version: "3.8"
services:
  app:
    container_name: glfw
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: development
      args:
        - USERNAME=${CONTAINER_USER}
    volumes:
      # Host workspace
      - type: bind
        source: ${HOST_WORKSPACE}
        target: ${CONTAINER_WORKSPACE}
        consistency: cached
        
      # X11 settings
      - type: bind
        source: /home/${HOST_USER}/.Xauthority
        target: /home/${CONTAINER_USER}/.Xauthority
        read_only: true
      - /tmp/.X11-unix:/tmp/.X11-unix:ro

      # Soocket dir for inter container communication
      - ${SOCKET_DIR}:${SOCKET_DIR} # for socket
    environment:
      # We hard-code the X11 display delimiter ":" in here
      # This workaround is because of unreliable behavior of docker-compose substituting ":" in docker-compose.yml from .env file
      - DISPLAY=:${DISPLAY}
    user: ${CONTAINER_USER}

    # Uncomment the following IPC option if one wants to connect docker_ximea container
    ipc: container:ximea

    tty: true

    # Overrides default command so things don't shut down after the process ends.
    # We also change the owner of the host's tmp folder for socket communication
    command: >
      /bin/sh -c 
      "sudo chown -R ${CONTAINER_USER}:${CONTAINER_USER} ${SOCKET_DIR};
      while sleep 1000; do :; done"