version: "3.8"
services:
  app:
    container_name: pytorch
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: development
      args:
        - USERNAME=${CONTAINER_USER}
    volumes:
      # Host workspace
      - type: bind
        source: ${HOST_WORKSPACE}
        target: ${CONTAINER_WORKSPACE}
        consistency: cached
      # ZMQ socket
      # for inter container communication via ZeroMQ
      - /tmp/zmq:/tmp/zmq 
    user: ${CONTAINER_USER}
    tty: true
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"