version: "3.8"
services:
  app:
    container_name: ximea
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: development
      args:
        - USERNAME=${CONTAINER_USER}
        - SOCKET_DIR=${SOCKET_DIR} # for socket
    volumes:
      # Host workspace
      - type: bind
        source: ${HOST_WORKSPACE}
        target: ${CONTAINER_WORKSPACE}
        consistency: cached
      # Soocket dir for inter container communication
      - ${SOCKET_DIR}:${SOCKET_DIR} # for socket
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    user: ${CONTAINER_USER}
    
    # IPC Mode sharable 
    ipc: shareable

    tty: true

    # Overrides default command so things don't shut down after the process ends.
    # We also change the owner of the host's tmp folder for socket communication
    command: >
      /bin/sh -c 
      "sudo chown -R ${CONTAINER_USER}:${CONTAINER_USER} ${SOCKET_DIR};
      while sleep 1000; do :; done"
