version: "3.8"
services:
  app:
    container_name: ximea
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: development
    volumes:
      # Host workspace
      - /home/avl/Repositories:/workspace:cached
      # ZMQ socket
      # for inter container communication via ZeroMQ
      - /tmp/zmq:/tmp/zmq
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    tty: true
    # network_mode: "docker_shared"
    # expose:
    #   - "8221"
    command: /bin/sh -c "while sleep 1000; do :; done"